services:
  router1:
    build:
      context: .
      dockerfile: router.Dockerfile
    container_name: router1
    volumes:
      - ./frr-config/frr1:/etc/frr
    ports:
      - "2222:22"
    networks:
      net:
        ipv4_address: 172.28.0.2

  router2:
    build:
      context: .
      dockerfile: router.Dockerfile
    container_name: router2
    volumes:
      - ./frr-config/frr2:/etc/frr
    ports:
      - "2223:22"
    networks:
      net:
        ipv4_address: 172.28.0.3

  lg:
    build:
      context: .
      dockerfile: lg.Dockerfile
    container_name: lg
    volumes:
      - ./lg-config:${CONFIG_PATH:-/etc/lg-config}
    environment:
      - CONFIG_PATH=${CONFIG_PATH:-/etc/lg-config}
    ports:
      - "8000:80"
    networks:
      net:
        ipv4_address: 172.28.0.4

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
